// Generated by CoffeeScript 1.3.1

Tower.Model.Attachment = {
  ClassMethod: {
    attachment: function(name, options) {
      if (options == null) {
        options = {};
      }
    },
    attachments: function() {
      return this.metadata().attachments;
    }
  }
};

module.exports = Tower.Model.Attachment;
